uv run src/finetune_vibevoice_lora.py ^
--model_name_or_path Jmica/VibeVoice7B ^
--processor_name_or_path Jmica/VibeVoice7B ^
--train_jsonl rissa_vibevoice_dataset/rissa_train.jsonl ^
--text_column_name text ^
--audio_column_name audio ^
--output_dir output_test ^
--per_device_train_batch_size 8 ^
--gradient_accumulation_steps 16 ^
--learning_rate 2.5e-5 ^
--num_train_epochs 5 ^
--logging_steps 1000 ^
--save_steps 1000 ^
--eval_steps 1000 ^
--remove_unused_columns False ^
--bf16 True ^
--do_train ^
--gradient_clipping ^
--gradient_checkpointing False ^
--ddpm_batch_mul 4 ^
--diffusion_loss_weight 1.4 ^
--train_diffusion_head True ^
--ce_loss_weight 0.04 ^
--voice_prompt_drop_rate 0.2 ^
--lora_target_modules q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj ^
--lr_scheduler_type cosine ^
--warmup_ratio 0.03 ^
--max_grad_norm 0.8